// src/components/HomeScreen.tsx
import { setUsername, getUsername } from '../globals';
import { socket } from '../socket'; // make sure you’re importing your initialized socket
import './HomeScreen.css';
//import logo from '../assets/logo.webp';

export interface HomeScreenProps {
  onCreate: (lobbyId: number) => void;
  onJoin: () => void;
}

export function HomeScreen({ onCreate, onJoin }: HomeScreenProps) {
  const currentName = getUsername();

  function setUsernameFromInput(): void {
    const el = document.getElementById('usernameInput') as HTMLInputElement | null;
    setUsername(el ? el.value : '');
  }

  function createLobby(): void {
    setUsernameFromInput();
    const username = getUsername().trim();
    if (!username) {
      alert('Please enter a username');
      return;
    }

    // Emit to server to create a lobby. Server will respond with a real numeric ID.
    socket.emit(
      'createLobby',
      username,
      (response: { success: boolean; lobbyId?: number; error?: string }) => {
        if (!response.success || response.lobbyId === undefined) {
          alert('Could not create lobby: ' + (response.error || 'Unknown error'));
          return;
        }
        // Now we have a real lobbyId generated by the server:
        onCreate(response.lobbyId);
      }
    );
  }

  return (
    <div className="main-wrapper">
      <h1>Element-Jitsu</h1>

      <div className="page-wrapper">
        <input
          id="usernameInput"
          type="text"
          defaultValue={currentName}
          placeholder="Enter username"
          className="username-input"
          onChange={setUsernameFromInput}
        />

        <div className="button-row">
          <button className="action-btn" onClick={createLobby}>
            Create Lobby
          </button>
          <button className="action-btn" onClick={onJoin}>
            Join Lobby
          </button>
        </div>
      </div>
    </div>
  );
}
